#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : re2c
Version  : 2.0.1
Release  : 10
URL      : https://github.com/skvadrik/re2c/releases/download/2.0.1/re2c-2.0.1.tar.xz
Source0  : https://github.com/skvadrik/re2c/releases/download/2.0.1/re2c-2.0.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Public-Domain
Requires: re2c-bin = %{version}-%{release}
Requires: re2c-data = %{version}-%{release}
Requires: re2c-license = %{version}-%{release}
Requires: re2c-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-golang

%description
DESCRIPTION
-----------
re2c is a free and open-source lexer generator for C, C++ and Go.

%package bin
Summary: bin components for the re2c package.
Group: Binaries
Requires: re2c-data = %{version}-%{release}
Requires: re2c-license = %{version}-%{release}

%description bin
bin components for the re2c package.


%package data
Summary: data components for the re2c package.
Group: Data

%description data
data components for the re2c package.


%package license
Summary: license components for the re2c package.
Group: Default

%description license
license components for the re2c package.


%package man
Summary: man components for the re2c package.
Group: Default

%description man
man components for the re2c package.


%prep
%setup -q -n re2c-2.0.1
cd %{_builddir}/re2c-2.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1596151339
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1596151339
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/re2c
cp %{_builddir}/re2c-2.0.1/LICENSE %{buildroot}/usr/share/package-licenses/re2c/4bc5a5deebfea79e0d2d5b428a6bfd9a6d239959
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/re2c

%files data
%defattr(-,root,root,-)
/usr/share/re2c/stdlib/unicode_categories.re

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/re2c/4bc5a5deebfea79e0d2d5b428a6bfd9a6d239959

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/re2c.1
