#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : re2c
Version  : 1.3
Release  : 8
URL      : https://github.com/skvadrik/re2c/releases/download/1.3/re2c-1.3.tar.xz
Source0  : https://github.com/skvadrik/re2c/releases/download/1.3/re2c-1.3.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Public-Domain
Requires: re2c-bin = %{version}-%{release}
Requires: re2c-data = %{version}-%{release}
Requires: re2c-man = %{version}-%{release}
BuildRequires : bison

%description
DESCRIPTION
-----------
re2c is a free and open-source lexer generator for C and C++.

%package bin
Summary: bin components for the re2c package.
Group: Binaries
Requires: re2c-data = %{version}-%{release}

%description bin
bin components for the re2c package.


%package data
Summary: data components for the re2c package.
Group: Data

%description data
data components for the re2c package.


%package man
Summary: man components for the re2c package.
Group: Default

%description man
man components for the re2c package.


%prep
%setup -q -n re2c-1.3
cd %{_builddir}/re2c-1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1587481869
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1587481869
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/re2c

%files data
%defattr(-,root,root,-)
/usr/share/re2c/stdlib/unicode_categories.re

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/re2c.1
